In [22]:
import pandas as pd
import numpy as np

In [23]:
data = pd.read_csv('Kolkata.csv')

In [24]:
data.drop(columns=['Gymnasium'])

,Price,Area,Location,No. of Bedrooms,No. of Bathrooms,SwimmingPool,CarParking,AC,LiftAvailable
0,2235000,1016,Barasat,3,3,1,0,0,1
1,3665999,1111,Keshtopur,2,2,0,0,0,0
2,3774000,1020,Rajarhat,2,2,0,0,0,1
3,2524000,935,Narendrapur,2,2,1,0,0,0
4,8300000,1956,New Town,3,3,1,1,0,1
...,...,...,...,...,...,...,...,...,...
6501,4208000,1570,Lake Town,3,3,9,9,9,9
6502,10100000,1208,Narendrapur,3,3,9,9,9,9
6503,6669000,815,Rajarhat,2,2,9,9,9,9
6504,4608000,952,Kaikhali,2,2,9,9,9,9
6505,9148000,1130,Howrah,2,2,9,9,9,9

In [25]:
data.dropna(inplace=True)

In [26]:
print(data.columns)

Index(['Price', 'Area', 'Location', 'No. of Bedrooms', 'No. of Bathrooms',
       'Gymnasium', 'SwimmingPool', 'CarParking', 'AC', 'LiftAvailable'],
      dtype='object')

In [27]:
data['Location']=data['Location'].apply(lambda x:x.strip())

In [28]:
data['Location'].value_counts()

Location
New Town             711
Rajarhat             405
Tangra               369
Dum Dum              316
Garia                307
                    ...
Nayabad Daspara        1
Bangur avenue          1
Ganguly Para           1
Jodthbhim Newtown      1
Durganagar             1
Name: count, Length: 308, dtype: int64

In [29]:
Location_stats = data.groupby('Location')['Location'].agg('count').sort_values(ascending=False)

In [30]:
Locations_less_than_10_entries = Location_stats[Location_stats<=10]

In [31]:
Locations_less_than_10_entries

Location
Airport                               10
Topsia Road                           10
Action Area III                       10
Baghajatin                            10
Ganguly Bagan                         10
                                      ..
Bangur avenue                          1
Bally Khal                             1
Tagore Park Road                       1
Taltala                                1
Acharya Jagadish Chandra Bose Road     1
Name: Location, Length: 230, dtype: int64

In [32]:
data['Location']=data['Location'].apply(lambda x:'other' if x in Locations_less_than_10_entries else x)

In [33]:
data['Location'].value_counts()

Location
New Town                        711
other                           709
Rajarhat                        405
Tangra                          369
Dum Dum                         316
                               ...
Kamalgazi                        12
Durgapur                         12
Hooghly Chinsurah                11
Elgin                            11
N S C Bose Road  Narendrapur     11
Name: count, Length: 79, dtype: int64

In [34]:
data

,Price,Area,Location,No. of Bedrooms,No. of Bathrooms,Gymnasium,SwimmingPool,CarParking,AC,LiftAvailable
0,2235000,1016,Barasat,3,3,1,1,0,0,1
1,3665999,1111,Keshtopur,2,2,1,0,0,0,0
2,3774000,1020,Rajarhat,2,2,1,0,0,0,1
3,2524000,935,Narendrapur,2,2,1,1,0,0,0
4,8300000,1956,New Town,3,3,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...
6501,4208000,1570,Lake Town,3,3,9,9,9,9,9
6502,10100000,1208,Narendrapur,3,3,9,9,9,9,9
6503,6669000,815,Rajarhat,2,2,9,9,9,9,9
6504,4608000,952,Kaikhali,2,2,9,9,9,9,9
6505,9148000,1130,Howrah,2,2,9,9,9,9,9

In [40]:
data.Area.unique()

array([1016, 1111, 1020, ..., 1002, 1369,  968])

In [41]:
data.dropna(inplace=True)

,Price,Area,No. of Bedrooms,No. of Bathrooms,Gymnasium,SwimmingPool,CarParking,AC,LiftAvailable
count,6.506000e+03,6506.000000,6506.000000,6506.000000,6506.000000,6506.000000,6506.000000,6506.000000,6506.000000
mean,8.492970e+06,1344.054719,2.630956,2.630956,8.903013,8.901629,8.901476,8.897018,8.905011
std,1.460640e+07,807.709428,0.712135,0.712135,0.899722,0.912552,0.913966,0.954056,0.880858
min,2.000000e+06,350.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.300000e+06,920.000000,2.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000
50%,4.940000e+06,1144.000000,3.000000,3.000000,9.000000,9.000000,9.000000,9.000000,9.000000
75%,8.000000e+06,1454.000000,3.000000,3.000000,9.000000,9.000000,9.000000,9.000000,9.000000
max,5.040000e+08,10000.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000

In [42]:
data.describe()

,Price,Area,No. of Bedrooms,No. of Bathrooms,Gymnasium,SwimmingPool,CarParking,AC,LiftAvailable
count,6.506000e+03,6506.000000,6506.000000,6506.000000,6506.000000,6506.000000,6506.000000,6506.000000,6506.000000
mean,8.492970e+06,1344.054719,2.630956,2.630956,8.903013,8.901629,8.901476,8.897018,8.905011
std,1.460640e+07,807.709428,0.712135,0.712135,0.899722,0.912552,0.913966,0.954056,0.880858
min,2.000000e+06,350.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.300000e+06,920.000000,2.000000,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000
50%,4.940000e+06,1144.000000,3.000000,3.000000,9.000000,9.000000,9.000000,9.000000,9.000000
75%,8.000000e+06,1454.000000,3.000000,3.000000,9.000000,9.000000,9.000000,9.000000,9.000000
max,5.040000e+08,10000.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000

In [45]:
data

,Price,Area,Location,No. of Bedrooms,No. of Bathrooms,Gymnasium,SwimmingPool,CarParking,AC,LiftAvailable
0,2235000,1016,Barasat,3,3,1,1,0,0,1
1,3665999,1111,Keshtopur,2,2,1,0,0,0,0
2,3774000,1020,Rajarhat,2,2,1,0,0,0,1
3,2524000,935,Narendrapur,2,2,1,1,0,0,0
4,8300000,1956,New Town,3,3,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...
6501,4208000,1570,Lake Town,3,3,9,9,9,9,9
6502,10100000,1208,Narendrapur,3,3,9,9,9,9,9
6503,6669000,815,Rajarhat,2,2,9,9,9,9,9
6504,4608000,952,Kaikhali,2,2,9,9,9,9,9
6505,9148000,1130,Howrah,2,2,9,9,9,9,9

In [50]:
data.drop(columns=['Gymnasium','SwimmingPool','CarParking','AC','LiftAvailable'],axis =1,inplace=True)

KeyError: "['Gymnasium', 'SwimmingPool', 'CarParking', 'AC', 'LiftAvailable'] not found in axis"

In [51]:
data

         Price  Area     Location  No. of Bedrooms  No. of Bathrooms
0      2235000  1016      Barasat                3                 3
1      3665999  1111    Keshtopur                2                 2
2      3774000  1020     Rajarhat                2                 2
3      2524000   935  Narendrapur                2                 2
4      8300000  1956     New Town                3                 3
...        ...   ...          ...              ...               ...
6501   4208000  1570    Lake Town                3                 3
6502  10100000  1208  Narendrapur                3                 3
6503   6669000   815     Rajarhat                2                 2
6504   4608000   952     Kaikhali                2                 2
6505   9148000  1130       Howrah                2                 2

[6506 rows x 5 columns]

In [69]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split

col_trans = make_column_transformer(
    (OneHotEncoder(sparse_output=False), ['Location']),
    remainder='passthrough'
)

lr = LinearRegression()
scaler = StandardScaler()

model = make_pipeline(col_trans, scaler, lr)

In [ ]:
col_trans=make_column_transformer((OneHotEncoder(sparse_output=False),['Location']),remainder='passthrough')

In [59]:
data_input= data.drop(columns = ['Price'])
data_output=data['Price']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(data_input, data_output, test_size=0.2, random_state=42)
model.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [75]:
model.score(x_test, y_test)

-0.058884382104032795

In [83]:
input=pd.DataFrame([[1200,'Barasat',3,2]], columns =['Area','Location','No. of Bedrooms','No. of Bathrooms'])

In [85]:
model.predict(input)

array([3803626.90979404])

In [87]:
import pickle as pk

In [88]:
pk.dump(model,open('House_Prediction_Model.pkl','wb'))

In [89]:
data.to_csv('cleaned_data.csv')